version: "3.8"

services:
  db:
    image: postgres:16-bullseye
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./CREATE_1.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  app:
    build: ./
    volumes:
      - .:/app
    ports:
      - 8080:8080
    command: ["/main"]
    depends_on:
      - db
